version: '3'

services:

  php:
    image: ghcr.io/ld-web/php-apache:8.2
    volumes:
      - ./html:/var/www/html/
    ports:
      - '${PHP_PORT}:80' #.env

  mysql:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} #.env
      MYSQL_USER: ${MYSQL_USER} #.env
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} #.env
    ports:
      - '${MYSQL_PORT}:3306' #.env
    volumes:
      - ./.mysql/data:/var/lib/mysql
      - ./.mysql/scripts:/scripts # TODO : gather more info on how to manage scripts the right way (dedicated folder)

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: ${MYSQL_PORT} #.env
      PMA_USER: ${PMA_LOGIN} #.env
      PMA_PASSWORD: ${PMA_PASSWORD} #.env
      UPLOAD_LIMIT: 512M
    ports:
      - '${PMA_PORT}:80' #.env
    depends_on:
      - mysql

  # TODO : Add adminer